AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  
Resources:
  LogicalID:
    Type: AWS::EC2::Instance
    Properties:
        ImageId: "String"
        InstanceType: "String"
      Ipv6AddressCount: Number
      Ipv6Addresses:
        Ipv6Addresses
      KernelId: "String"
      KeyName: "String"
      LaunchTemplate:
        LaunchTemplateId: "String"
        LaunchTemplateName: "String"
        Version: "String"
      LicenseSpecifications:
        LicenseSpecifications
      Monitoring: String
      NetworkInterfaces:
        NetworkInterfaces
      PlacementGroupName: "String"
      PrivateDnsNameOptions:
        EnableResourceNameDnsAAAARecord: false
        EnableResourceNameDnsARecord: false
        HostnameType: "String"
      PrivateIpAddress: "false"
      PropagateTagsToVolumeOnCreation: String
      RamdiskId: "String"
      SecurityGroupIds:
        SecurityGroupIds
      SecurityGroups:
        SecurityGroups
      SourceDestCheck: false
      SsmAssociations:
        SsmAssociations
      SubnetId: "String"
      Tags:
        Tags
      Tenancy: "String"
      UserData: "String"
      Volumes:
        Volumes
Outputs: